# Generated by Django 4.0.3 on 2023-03-10 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('news_categroy', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户浏览新闻类别')),
                ('news_keyword', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户浏览新闻关键词')),
                ('news_histroy', models.TextField(blank=True, null=True, verbose_name='用户浏览新闻记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户特征',
                'verbose_name_plural': '用户特征',
                'db_table': 'tb_usercharacters',
            },
        ),
    ]
