# Generated by Django 4.0.3 on 2023-03-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usercharacters_news_categroy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercharacters',
            name='news_keyword',
            field=models.TextField(blank=True, null=True, verbose_name='用户浏览新闻关键词'),
        ),
    ]
