# Generated by Django 4.0.3 on 2023-03-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usercharacters_news_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercharacters',
            old_name='news_categroy_interested',
            new_name='news_categroy_Poi',
        ),
    ]
