# Generated by Django 4.0.3 on 2023-03-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_news_categroy_interested_usercharacters_news_categroy_poi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercharacters',
            old_name='news_histroy',
            new_name='news_history',
        ),
    ]
