# Generated by Django 4.0.3 on 2023-03-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscharacters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscharacters',
            options={'verbose_name': '新闻特征', 'verbose_name_plural': '新闻特征'},
        ),
        migrations.AlterModelTable(
            name='newscharacters',
            table='tb_newscharacters',
        ),
    ]
