# Generated by Django 4.0.3 on 2023-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newscharacters_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscharacters',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='新闻关键词'),
        ),
    ]
